import { db } from '@/modules/darussalam/db';
import type { Room, Idea } from '@/modules/darussalam/types';

function makeId(prefix: string) {
  return `${prefix}_${Math.random().toString(36).slice(2, 10)}${Date.now().toString(36)}`;
}

export async function seedDarussalamIfEmpty() {
  const roomCount = await db.rooms.count();
  if (roomCount > 0) return;

  const now = Date.now();
  const day = 86_400_000;

  const rooms: Room[] = [
    {
      id: 'room_kitchen',
      name: 'Kitchen',
      tagline: 'Where flavor creates memories',
      icon: 'kitchen',
      category: 'indoor',
      description: 'The heart of our home. A space for cooking, connecting and creating beautiful memories together.',
      moodStyle: 'Tropical Modern',
      moodTags: ['Warm', 'Functional', 'Open', 'Natural Light'],
      colorPalette: ['#4F6A45', '#C9B18C', '#A9702F', '#F0E9DD', '#B7C9A8'],
      materials: ['Wood', 'Rattan', 'Marble', 'Plants'],
      requirements: [
        { id: 'r1', label: 'Island with seating for 3', done: true },
        { id: 'r2', label: 'Ample storage & tall pantry', done: true },
        { id: 'r3', label: 'Good natural light', done: true },
        { id: 'r4', label: 'Easy access to backyard', done: true },
        { id: 'r5', label: 'Space for double door fridge', done: false },
        { id: 'r6', label: 'Separate area for appliances', done: false },
      ],
      progress: {
        ideas: { current: 128, target: 150 },
        measurements: { current: 18, target: 25 },
        decisions: { current: 9, target: 15 },
        documents: { current: 6, target: 12 },
      },
      measurementsCount: 18,
      documentsCount: 6,
      notesCount: 4,
      order: 0,
      favorite: true,
      createdAt: now - 60 * day,
      updatedAt: now - day,
    },
    {
      id: 'room_living',
      name: 'Living Room',
      tagline: 'Gather. Relax. Connect.',
      icon: 'livingRoom',
      category: 'indoor',
      description: 'A welcoming space for family and guests to unwind together.',
      moodTags: ['Cozy', 'Open'],
      measurementsCount: 5,
      documentsCount: 2,
      notesCount: 3,
      order: 1,
      createdAt: now - 55 * day,
      updatedAt: now - 3 * day,
    },
    {
      id: 'room_prayer',
      name: 'Prayer Room',
      tagline: 'A space for peace and reflection',
      icon: 'prayerRoom',
      category: 'indoor',
      description: 'A quiet corner facing the qibla, kept simple and calm.',
      moodTags: ['Calm', 'Minimal'],
      measurementsCount: 3,
      documentsCount: 1,
      notesCount: 2,
      order: 2,
      createdAt: now - 50 * day,
      updatedAt: now - 5 * day,
    },
    {
      id: 'room_master',
      name: 'Master Bedroom',
      tagline: 'Rest. Recharge. Renew.',
      icon: 'bedroom',
      category: 'indoor',
      measurementsCount: 6,
      documentsCount: 1,
      notesCount: 2,
      order: 3,
      createdAt: now - 45 * day,
      updatedAt: now - 2 * day,
    },
    {
      id: 'room_garden',
      name: 'Garden',
      tagline: 'Nature that soothes the soul',
      icon: 'garden',
      category: 'outdoor',
      measurementsCount: 2,
      documentsCount: 0,
      notesCount: 1,
      order: 4,
      createdAt: now - 40 * day,
      updatedAt: now - day,
    },
    {
      id: 'room_garage',
      name: 'Garage',
      tagline: 'Functional. Organized. Simple.',
      icon: 'garage',
      category: 'other',
      measurementsCount: 1,
      documentsCount: 0,
      notesCount: 0,
      order: 5,
      createdAt: now - 35 * day,
      updatedAt: now - 10 * day,
    },
    {
      id: 'room_entrance',
      name: 'Entrance',
      tagline: 'The first welcome home',
      icon: 'entrance',
      category: 'indoor',
      measurementsCount: 1,
      documentsCount: 0,
      notesCount: 1,
      order: 6,
      createdAt: now - 30 * day,
      updatedAt: now - 2 * 3600_000,
    },
    {
      id: 'room_staircase',
      name: 'Staircase',
      tagline: 'Every step designed with care',
      icon: 'staircase',
      category: 'indoor',
      measurementsCount: 1,
      documentsCount: 0,
      notesCount: 0,
      order: 7,
      createdAt: now - 28 * day,
      updatedAt: now - day,
    },
  ];

  const ideas: Idea[] = [
    {
      id: makeId('idea'),
      roomId: 'room_entrance',
      type: 'note',
      title: 'Hidden shoe cabinet under staircase',
      description: 'Saw this on a reel — pull-out shoe storage tucked under the stairs.',
      tag: 'Storage',
      createdAt: now - 2 * 3600_000,
      updatedAt: now - 2 * 3600_000,
    },
    {
      id: makeId('idea'),
      roomId: 'room_staircase',
      type: 'note',
      title: 'Skylight above staircase',
      description: 'For natural light in the stairwell.',
      tag: 'Lighting',
      createdAt: now - day,
      updatedAt: now - day,
    },
    {
      id: makeId('idea'),
      roomId: 'room_living',
      type: 'note',
      title: 'Wooden slat wall for TV unit',
      description: 'Warm wood texture behind the TV, hides wiring too.',
      tag: 'Wall',
      createdAt: now - 2 * day,
      updatedAt: now - 2 * day,
    },
    {
      id: makeId('idea'),
      roomId: 'room_garden',
      type: 'note',
      title: 'Courtyard with water feature',
      description: 'Peaceful vibe in the center of the house.',
      tag: 'Garden',
      createdAt: now - 10 * 60_000,
      updatedAt: now - 10 * 60_000,
    },
    {
      id: makeId('idea'),
      roomId: 'room_entrance',
      type: 'note',
      title: 'Pull-out shoe cabinet',
      description: 'Under staircase for extra storage.',
      tag: 'Entrance',
      createdAt: now - 60 * 60_000,
      updatedAt: now - 60 * 60_000,
    },
    {
      id: makeId('idea'),
      roomId: 'room_kitchen',
      type: 'note',
      title: 'Rattan pendant lights over the island',
      tag: 'Lighting',
      createdAt: now - 6 * day,
      updatedAt: now - 6 * day,
    },
    {
      id: makeId('idea'),
      roomId: 'room_kitchen',
      type: 'note',
      title: 'Open shelving with potted herbs',
      tag: 'Storage',
      createdAt: now - 8 * day,
      updatedAt: now - 8 * day,
    },
    {
      id: makeId('idea'),
      roomId: 'room_kitchen',
      type: 'note',
      title: 'Backyard-facing window above the sink',
      tag: 'Layout',
      createdAt: now - 12 * day,
      updatedAt: now - 12 * day,
    },
  ];

  await db.rooms.bulkAdd(rooms);
  await db.ideas.bulkAdd(ideas);
}
