export const modules = [
  {
    key: 'nazara',
    title: 'Nazara',
    subtitle: 'Memories',
    description: 'Capture and cherish moments.',
    image: '/design-icons/nazara.png',
    icon: 'camera',
    cardBg: 'bg-accent-orange-bg',
    iconBg: 'bg-card-bg',
    iconFg: 'text-accent-orange-fg',
    subtitleColor: 'text-accent-orange-fg',
    enabled: true,
  },
  {
    key: 'hisaab',
    title: 'Hisaab',
    subtitle: 'Finance & Assets',
    description: 'Manage your money, assets and valuables.',
    image: '/design-icons/hisaab.png',
    icon: 'wallet',
    cardBg: 'bg-accent-green-bg',
    iconBg: 'bg-card-bg',
    iconFg: 'text-accent-green-fg',
    subtitleColor: 'text-accent-green-fg',
    enabled: true,
  },
  {
    key: 'amaanat',
    title: 'Amaanat',
    subtitle: 'Everything entrusted to your care',
    description: 'Track your items, invoices and warranties.',
    image: '/design-icons/amaanat.svg',
    icon: 'shield',
    cardBg: 'bg-accent-purple-bg',
    iconBg: 'bg-card-bg',
    iconFg: 'text-accent-purple-fg',
    subtitleColor: 'text-accent-purple-fg',
    enabled: true,
  },
  {
    key: 'sanad',
    title: 'Sanad',
    subtitle: 'What proves it',
    description: 'Store, manage and get reminded before they expire.',
    image: null,
    icon: 'fileCheck',
    cardBg: 'bg-accent-blue-bg',
    iconBg: 'bg-card-bg',
    iconFg: 'text-accent-blue-fg',
    subtitleColor: 'text-accent-blue-fg',
    enabled: true,
  },
  {
    key: 'dua',
    title: 'Dua',
    subtitle: 'Keep your supplications close',
    description: 'A calm, personal library of duas, adhkar and ratibs.',
    image: null,
    icon: 'bookOpen',
    cardBg: 'bg-accent-pink-bg',
    iconBg: 'bg-card-bg',
    iconFg: 'text-accent-pink-fg',
    subtitleColor: 'text-accent-pink-fg',
    enabled: true,
  },
  {
    key: 'wishbook',
    title: 'Wishbook',
    subtitle: 'Dreams & Desires',
    description: 'Track the things you hope to bring into your life.',
    image: null,
    icon: 'star',
    cardBg: 'bg-[#FFF3DC]',
    iconBg: 'bg-card-bg',
    iconFg: 'text-[#C8922E]',
    subtitleColor: 'text-[#C8922E]',
    enabled: true,
  },
  {
    key: 'done',
    title: 'Done',
    subtitle: 'Habits',
    description: 'Small actions. Big progress.',
    image: null,
    icon: 'sprout',
    cardBg: 'bg-accent-doneGreen-bg',
    iconBg: 'bg-card-bg',
    iconFg: 'text-accent-doneGreen-fg',
    subtitleColor: 'text-accent-doneGreen-fg',
    enabled: true,
  },
  {
    key: 'darussalam',
    title: 'Darussalam',
    subtitle: 'Dream Home Notebook',
    description: 'Capture every idea before your home is built.',
    image: null,
    icon: 'treePine',
    cardBg: 'bg-darussalam-tile',
    iconBg: 'bg-card-bg',
    iconFg: 'text-darussalam-green',
    subtitleColor: 'text-darussalam-green',
    enabled: true,
  },
  {
    key: 'journey',
    title: 'Journey',
    subtitle: 'Plans & Experiences',
    description: 'Plan, track and remember your trips.',
    image: null,
    icon: 'mapPin',
    cardBg: 'bg-accent-orange-bg',
    iconBg: 'bg-card-bg',
    iconFg: 'text-accent-orange-fg',
    subtitleColor: 'text-accent-orange-fg',
    enabled: false,
  },
] as const;

export const bottomNavItems = [
  { key: 'nazara',   label: 'Nazara',   path: '/nazara' },
  { key: 'hisaab',  label: 'Hisaab',   path: '/hisaab' },
  { key: 'amaanat', label: 'Amaanat',  path: '/amaanat' },
  { key: 'sanad',   label: 'Sanad',    path: '/sanad' },
  { key: 'dua',     label: 'Dua',      path: '/dua' },
  { key: 'wishbook',label: 'Wishbook', path: '/wishbook' },
] as const;
