export const modules = [
  {
    key: 'nazara',
    title: 'Nazara',
    subtitle: 'Memories',
    description: 'Capture and cherish moments.',
    image: '/design-icons/nazara.png',
    icon: 'camera',
    cardBg: 'bg-accent-orange-bg',
    iconBg: 'bg-card-bg',
    iconFg: 'text-accent-orange-fg',
    subtitleColor: 'text-accent-orange-fg',
    enabled: true,
  },
  {
    key: 'hisaab',
    title: 'Hisaab',
    subtitle: 'Finance & Assets',
    description: 'Manage your money, assets and valuables.',
    image: '/design-icons/hisaab.png',
    icon: 'wallet',
    cardBg: 'bg-accent-green-bg',
    iconBg: 'bg-card-bg',
    iconFg: 'text-accent-green-fg',
    subtitleColor: 'text-accent-green-fg',
    enabled: true,
  },
  {
    key: 'amaanat',
    title: 'Amaanat',
    subtitle: 'Everything entrusted to your care',
    description: 'Track your items, invoices and warranties.',
    image: '/design-icons/amaanat.svg',
    icon: 'shield',
    cardBg: 'bg-accent-purple-bg',
    iconBg: 'bg-card-bg',
    iconFg: 'text-accent-purple-fg',
    subtitleColor: 'text-accent-purple-fg',
    enabled: true,
  },
  {
    key: 'sanad',
    title: 'Sanad',
    subtitle: 'What proves it',
    description: 'Store, manage and get reminded before they expire.',
    image: null,
    icon: 'fileCheck',
    cardBg: 'bg-accent-blue-bg',
    iconBg: 'bg-card-bg',
    iconFg: 'text-accent-blue-fg',
    subtitleColor: 'text-accent-blue-fg',
    enabled: true,
  },
  {
    key: 'dua',
    title: 'Dua',
    subtitle: 'Keep your supplications close',
    description: 'A calm, personal library of duas, adhkar and ratibs.',
    image: null,
    icon: 'bookOpen',
    cardBg: 'bg-accent-pink-bg',
    iconBg: 'bg-card-bg',
    iconFg: 'text-accent-pink-fg',
    subtitleColor: 'text-accent-pink-fg',
    enabled: true,
  },
  {
    key: 'journey',
    title: 'Journey',
    subtitle: 'Plans & Experiences',
    description: 'Plan, track and remember your trips.',
    image: null,
    icon: 'mapPin',
    cardBg: 'bg-accent-orange-bg',
    iconBg: 'bg-card-bg',
    iconFg: 'text-accent-orange-fg',
    subtitleColor: 'text-accent-orange-fg',
    enabled: false,
  },
] as const;

export const bottomNavItems = [
  { key: 'home', label: 'Home', path: '/' },
  { key: 'hisaab', label: 'Hisaab', path: '/hisaab' },
  { key: 'amaanat', label: 'Amaanat', path: '/amaanat' },
  { key: 'sanad', label: 'Sanad', path: '/sanad' },
  { key: 'nazara', label: 'Nazara', path: '/nazara' },
] as const;
